### ISSUE TITLE
Implement approximate layout/design as per mockup

### ISSUE THREAD

**Issue by getdave** [Automattic/starter-page-templates#16]
Once [Template selection is working](https://github.com/Automattic/starter-page-templates/pull/12), implement the mockup shown on [this page](https://wp.me/paAmJe-lF).

We are not aiming for 1:1 perfection at this stage but something resembling this will improve the interactions.

@iamtakashi can advise on any design queries.

## Questions

- [ ] How can we access the core Gutenberg Sass setup so we can make use of existing `mixins` and variables?

**Comment by iamtakashi** [comment]
It might be too late and not matters much for this stage, but I'll mention this now for when we can improve the interactions.

* It'd be great if the page inserted when you click the thumbnail as opposed to select a template and click the button "Use Template". This will solve the issue that the button being pushed down when we have more templates or in a small screen. There is no big benefit having the "selected" state as you can only choose one template.
* Can be a blank page also a thumbnail? It might sound strange at first, but this can remove the small text link that can be easily overlooked.

<img width="826" alt="Screen Shot 2019-05-22 at 19 12 49" src="https://user-images.githubusercontent.com/908665/58198959-59e49700-7cc7-11e9-802d-d504af0f7131.png">
