### ISSUE TITLE
Create test site, export existing pages from the starter sites to act as Templates for demo purposes

### ISSUE THREAD

**Issue by obenland** [Automattic/starter-page-templates#2]

**Comment by frontdevde** [comment]
Created wp-PaZNBt-2 based on wp-PasQ7B-h

It's the home page only as the vertical starter sites currently don't have further pages. @iamtakashi is working on basic designs for additional pages.

We had originally thought it might be helpful to export existing reusable blocks from the vertical sites to allow for easier creation of the different pages. Currently, only the default vertical site wp-PaqEMq-2 stores reusable blocks. We ran into issues (see Slack conversation following /archives/CJS75TX3R/p1558525809069200) with the export and thus decided to can this part for now.

Rewording the issue title from `Create test site, export all Reusable Blocks from Business Vertical Site and import into test site` to `Export existing pages from the starter sites to act as Templates for demo purposes`.

**Comment by getdave** [comment]
@iamtakashi are you clear on what the task is here?

**Comment by frontdevde** [comment]
Solved for the demo by https://github.com/Automattic/starter-page-templates/pull/28
