### ISSUE TITLE
Add fallback experience for sites which haven't been allocated a Vertical

### ISSUE THREAD

**Issue by getdave** [Automattic/starter-page-templates#20]
If the site does not have a vertical assigned (ie: old sites) then we need to fallback to retrieving templates from a default starter site. These will be non-vertical specific.

See the link in the MT "Useful Resources" (https://wp.me/paAmJe-lF)

**Comment by marekhrabe** [comment]
still relevant task but closed in favor of main issue #8 where it is tracked as one of the todos
