### ISSUE TITLE
Dynamically determine the correct remote Vertical Starter Site based on data collected during onboarding

### ISSUE THREAD

**Issue by obenland** [Automattic/starter-page-templates#9]
Determine where the mapping lives for vertical to the vertical site that contains the templates.
Create API endpoint, lock that down, to only expose data based on the site vertical site option.
Authenticate by vertical ID, set in the user's wp_options

**Comment by marekhrabe** [comment]
I've passed this value from backend to frontend in https://github.com/Automattic/starter-page-templates/pull/23. 

Might not be needed in case we decide to handle all this stuff on backend but mentioning here just in case…

**Comment by marekhrabe** [comment]
became a part of #6
